"""
Utilities for processing the results generated by training jobs.
"""
import re
from pathlib import Path
from typing import Union

import pandas as pd
import torch
import yaml
from torchtnt.utils.flops import FlopTensorDispatchMode
from tqdm import tqdm

from assembly import model_from_config
from utils import load_yaml, num_params, num_trainable_params


def load_results(
        proj_dir: Union[Path, str],
        calc_sizes: bool = True,
        force_recalc: bool = False) -> tuple[list[pd.DataFrame], list[dict]]:
    """
    Scan for all result.pkl files in the given project folder and return them as a collection of dataframes with
    associated metadata.

    Args:
        proj_dir: The directory to scan recursively.
        calc_sizes: Whether to add model size data to the metadata. Requires loading of all models and takes some time.
            If done, will cache the sizes in the metadata so it doesn't need to be recalculated. NOTE: For FLOP
            calculation, we assume input tensors of size [3, 224, 224] and output vectors of size [1, 1000] (standard
            ImageNet format).
        force_recalc: Force a recalculation of all sizes, even if cached.

    Returns:
        results: List of result dataframes.
        metas: List of metadata associated with each corresponding result frame.
    """
    seed_pattern = re.compile(r"result-(\d+)\.pkl")

    cached_metas = {}
    metas = []
    results = []
    for resfile in tqdm(list(sorted(Path(proj_dir).rglob("result*.pkl")))):
        if not resfile.is_file():
            print(f"WARNING: Not a file: {resfile}")

        if resfile.parent not in cached_metas:
            metafile = resfile.parent / "metadata.yml"
            meta = load_yaml(metafile)
            if not meta:
                print(f"WARNING: Meta file is empty: {metafile}")
                continue
            cached_metas[resfile.parent] = meta
            if calc_sizes and (force_recalc or ("num_params" not in meta) or ("num_flops" not in meta)):
                cfg = load_yaml(resfile.parent / "config.yml")
                model = model_from_config(cfg, input_shape=[3, 224, 224], num_classes=1000)
                meta["num_params"] = num_params(model)
                meta["num_trainable_params"] = num_trainable_params(model)
                with FlopTensorDispatchMode(model) as ftdm:
                    dummy_img = torch.randn(1, 3, 224, 224)
                    _ = model(dummy_img)
                    meta["num_flops"] = sum(ftdm.flop_counts[""].values())
                # Write data back out to meta so we don't have to calc again.
                with open(metafile, "w") as f:
                    yaml.dump(meta, f)

        meta = cached_metas[resfile.parent].copy()  # Important to copy so we don't write to the original.
        metas.append(meta)
        try:
            meta["seed"] = int(seed_pattern.match(resfile.name).group(1))
        except AttributeError:
            print("Unable to parse seed:", resfile)
            raise
        results.append(pd.read_pickle(resfile))

    return results, metas


def combine_result_dataframes(results, metas):
    """
    Now combine results into a single dataframe. Each result gets tagged with metadata about the run that produced it.
    """
    # Ensure that the meta values are always listed in the same order, by defining that order ahead of time.
    # Make sure it's a superset of all available keys.
    meta_keys = set()
    for m in metas:
        meta_keys.update(m.keys())
    meta_keys = list(sorted(meta_keys))
    full_df = pd.concat(results, keys=[tuple(m[k] for k in meta_keys) for m in metas], names=meta_keys + ["Step"])
    full_df.set_index("Epoch", append=True, inplace=True)
    return full_df


def load_result_dataframe(proj_dir, calc_sizes=True, force_recalc=False) -> pd.DataFrame:
    """
    Scan for all result.pkl files in the given project folder and return them as a unified dataframe.

    Args:
        proj_dir: The directory to scan recursively.
        calc_sizes: Whether to add model size data to the metadata. Requires loading of all models and takes some time.
            If done, will cache the sizes in the metadata so it doesn't need to be recalculated.
        force_recalc: Force a recalculation of all sizes, even if cached.

    Returns:
        full_df: Data representing the training trajectories of all runs.
    """
    return combine_result_dataframes(*load_results(proj_dir, calc_sizes, force_recalc))


def last_epoch_only(full_df):
    """Filter the given dataframe down to just the final performance: i.e., the last epoch number."""
    # NOTE: This only works when all runs were done for the exact same number of epochs.
    #       Otherwise, we'd need to do a groupby and filter each group to its own max epoch.
    return full_df.loc[full_df.index.get_level_values("Epoch") == full_df.index.get_level_values("Epoch").max()]
