"""
Utilities for processing the results generated by training jobs.
"""
import re
from pathlib import Path
from typing import Any, Union

import pandas as pd
import torch
import yaml
from torchtnt.utils.flops import FlopTensorDispatchMode
from tqdm import tqdm

from assembly import model_from_config
from utils import load_yaml, num_params, num_trainable_params


def load_results(
        proj_dir: Union[Path, str],
        meta_required: bool = True,
        include_location: bool = False,
        calc_sizes: bool = True,
        force_recalc: bool = False) -> tuple[list[pd.DataFrame], list[dict]]:
    """
    Scan for all result.pkl files in the given project folder and return them as a collection of dataframes with
    associated metadata.

    Args:
        proj_dir: The directory to scan recursively.
        meta_required: Whether metadata.yml is required.
        include_location: Whether to add the directory relative to `proj_dir` as a meta attribute.
        calc_sizes: Whether to add model size data to the metadata. Requires loading of all models and takes some time.
            If done, will cache the sizes in the metadata so it doesn't need to be recalculated. NOTE: For FLOP
            calculation, we assume input tensors of size [3, 224, 224] and output vectors of size [1, 1000] (standard
            ImageNet format).
        force_recalc: Force a recalculation of all sizes, even if cached.

    Returns:
        results: List of result dataframes.
        metas: List of metadata associated with each corresponding result frame.
    """
    seed_pattern = re.compile(r"result-(\d+)\.pkl")

    cached_metas = {}
    metas = []
    results = []
    for resfile in tqdm(list(sorted(Path(proj_dir).rglob("result*.pkl")))):
        if not resfile.is_file():
            print(f"WARNING: Not a file: {resfile}")

        if resfile.parent not in cached_metas:
            metafile = resfile.parent / "metadata.yml"
            meta = load_yaml(metafile) if metafile.is_file() else {}
            if not meta and meta_required:
                print(f"WARNING: Meta file is empty: {metafile}")
                continue
            cached_metas[resfile.parent] = meta
            if include_location:
                meta["location"] = str(resfile.parent.relative_to(proj_dir))
            if calc_sizes and (force_recalc or ("num_params" not in meta) or ("num_flops" not in meta)):
                cfg = load_yaml(resfile.parent / "config.yml")
                model = model_from_config(cfg, input_shape=[3, 224, 224], num_classes=1000)
                meta["num_params"] = num_params(model)
                meta["num_trainable_params"] = num_trainable_params(model)
                with FlopTensorDispatchMode(model) as ftdm:
                    dummy_img = torch.randn(1, 3, 224, 224)
                    _ = model(dummy_img)
                    meta["num_flops"] = sum(ftdm.flop_counts[""].values())
                # Write data back out to meta so we don't have to calc again.
                with open(metafile, "w") as f:
                    yaml.dump(meta, f)

        meta = cached_metas[resfile.parent].copy()  # Important to copy so we don't write to the original.
        metas.append(meta)
        try:
            meta["seed"] = int(seed_pattern.match(resfile.name).group(1))
        except AttributeError:
            print("Unable to parse seed:", resfile)
            raise
        results.append(pd.read_pickle(resfile))

    return results, metas


def combine_result_dataframes(results: list[pd.DataFrame], metas: list[dict[str, Any]]) -> pd.DataFrame:
    """
    Now combine results into a single dataframe. Each result gets tagged with metadata about the run that produced it.
    """
    # Ensure that the meta values are always listed in the same order, by defining that order ahead of time.
    # Make sure it's a superset of all available keys.
    meta_keys = set()
    for m in metas:
        meta_keys.update(m.keys())
    meta_keys = list(sorted(meta_keys))

    # Epoch-based runs (supervised) carry an "Epoch" column which becomes an extra index level; the level named
    # "Step" is then just the row number, which is how this has always worked. Step-based runs (reinforcement
    # learning) have no "Epoch" at all, so index them by their actual step instead of the row number.
    have_epoch = ["Epoch" in r.columns for r in results]
    if any(have_epoch) and not all(have_epoch):
        raise RuntimeError("Cannot combine epoch-based and step-based results into one dataframe: "
                           f"{sum(have_epoch)} of {len(results)} results have an 'Epoch' column. Reinforcement "
                           "learning runs are step-indexed and supervised runs are epoch-indexed, so they need to be "
                           "loaded from separate directories.")
    epoch_based = all(have_epoch)
    if not epoch_based:
        results = [r.set_index("Step") if "Step" in r.columns else r for r in results]

    full_df = pd.concat(results, keys=[tuple(m[k] for k in meta_keys) for m in metas], names=meta_keys + ["Step"])
    if epoch_based:
        full_df.set_index("Epoch", append=True, inplace=True)
    return full_df


def load_result_dataframe(
        proj_dir: Union[Path, str],
        meta_required: bool = True,
        include_location: bool = False,
        calc_sizes: bool = True,
        force_recalc: bool = False) -> pd.DataFrame:
    """
    Scan for all result.pkl files in the given project folder and return them as a unified dataframe.

    Args:
        proj_dir: The directory to scan recursively.
        meta_required: Whether metadata.yml is required.
        include_location: Whether to add the directory relative to `proj_dir` as a meta attribute.
        calc_sizes: Whether to add model size data to the metadata. Requires loading of all models and takes some time.
            If done, will cache the sizes in the metadata so it doesn't need to be recalculated.
        force_recalc: Force a recalculation of all sizes, even if cached.

    Returns:
        full_df: Data representing the training trajectories of all runs.
    """
    return combine_result_dataframes(*load_results(proj_dir, meta_required, include_location, calc_sizes, force_recalc))


def last_epoch_only(full_df):
    """Filter the given dataframe down to just the final performance of each run: i.e., its last epoch number.

    Runs are identified by a unique index value; in other words, we group by all index columns (except "Step" and
    "Epoch"), and for each of these groups we take just the final epoch.
    """
    return _last_level_only(full_df, "Epoch")


def last_step_only(full_df, require=None):
    """Filter the given dataframe down to just the final performance of each run: i.e., its last step number.

    This is the step-indexed counterpart to `last_epoch_only()`, for runs which have no notion of an epoch (such as
    reinforcement learning runs).

    Args:
        full_df: Data representing the training trajectories of all runs.
        require: (Optional) Name of a column which must be non-null. Metrics which are only recorded periodically,
            such as evaluation results, are missing from most rows; pass the name of such a column to take the last
            step at which it was actually recorded, rather than the last step overall.
    """
    if require is not None:
        if require not in full_df.columns:
            raise ValueError(f"Column '{require}' not found in the results. Available columns:"
                             f" {list(full_df.columns)}")
        full_df = full_df[full_df[require].notna()]
    return _last_level_only(full_df, "Step")


def _last_level_only(full_df, level):
    """ Take, for each run, only the rows with the maximum value of the given index level. """
    group_levels = [name for name in full_df.index.names if name not in ("Step", "Epoch")]
    # By setting the series index to the same as the DF index, we make it possible to filter using '=='.
    values = pd.Series(full_df.index.get_level_values(level), index=full_df.index)
    max_values = values.groupby(level=group_levels).transform("max")
    return full_df.loc[values == max_values].copy()
